### PR TITLE
use root project versions in build.gradle

### PR DESCRIPTION
**Pull request by skb1129**
@CentaurWarchief Can you please merge this and create a new release on NPM?

### CODE REVIEW

**Comment by skb1129** [comment]
@andreyvital Can you please take a look at this.

**Comment by andreyvital** [comment]
@skb1129 does this break anything? I am not capable of testing right now

**Comment by andreyvital** [comment]
@skb1129 nevermind—LGTM. I'm merging and publishing! Thanks!

**Comment by andreyvital** [comment]
Published as `0.7.0`. Thanks man 🍻

**Pull request merged**
